### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by igarrido-adalab** [Adalab/modulo-2-evaluacion-intermedia-sarapalcam#1]
Really cool job @sarapalcam !!!

Here you have some tips to improve the exercise:

### JavaScript: advanced

- [x] Check if the `<select>` has the default option (with no value).
- [x] You can increase the user wins counter and the computer wins counter within the ifs of `compareResults()` function instead of re-check the result accesing to it in <https://github.com/Adalab/modulo-2-evaluacion-intermedia-sarapalcam/blob/b7abd2a1f931a570c866125178bda815b51204ee/js/main.js#L58-L66>

### Good practices

- [x] Try to improve your commits messages. "Add JS" is a bit poor. "Add random number logic" is more explanatory.

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Show an image with the user and computer selection
- Make the input work when selecting the option.
- Add a reset button that cleans the select, the counter and writes the initial feedback
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by igarridomorillas** [comment]
Perfect!
